server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brunoguilli/ead-config-server-repo
          defaultLabel: main
          username: brunoguilli
          password: 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

ead:
  configServer:
    username: configserver
    password: 'ead123cs'
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka/'
  instance:
    hostname: 'localhost'

